### ISSUE TITLE
Adapter pattern

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#1]
Podemos usar o adapter pattern para facilitar a integração com o backend, o que acham?

Links úteis:
https://sendgrid.com/blog/using-the-adapter-design-pattern-with-react/
https://bocoup.com/blog/adapter-pattern-a-must-for-vendor-service-integrations

**Comment by rafael1995** [comment]
Ainda não vi a fundo, mas acredito que isso pode nos ajudar 

https://github.com/dabit3/create-new-cli

**Comment by rafael1995** [comment]
Definido:  Uso do adapter será discutido após a implementação do axios.
