### ISSUE TITLE
Habilitar opção do github para esse repositorio

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/juggernaut#133]
Habiitar opção de "usar este template" no repositorio.

Fica mais fácil de começar um projeto usando o juggernaut.

Segue abaixo exemplo de um repositorio com o botão:

https://github.com/stanleygomes/nodevader

![image](https://user-images.githubusercontent.com/5298153/86532513-05878100-bea1-11ea-889e-f47882b9b6d3.png)

Como habilitar:

![image](https://user-images.githubusercontent.com/5298153/86532539-35cf1f80-bea1-11ea-8337-79f89a204612.png)

**Comment by vilaboim** [comment]
Done.
