### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#136]
We need to update our project dependencies.
In the last check I saw this outdated deps:
![Screen Shot 2020-10-02 at 11 21 11](https://user-images.githubusercontent.com/4191549/94934023-90c4e280-04a1-11eb-90c6-97dcfe58a763.png)

After update them you will need to test all npm scripts.

**Comment by ruturajkanake** [comment]
@vilaboim I would like to work on this issue. Can you assign it to me?
