### ISSUE TITLE
Material UI Kit

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#14]
Pelo que estudei a UI Kit mais madura que usa Material Design é esta aqui: https://material-ui.com/

Vocês conhecem outra?

**Comment by stanleygomes** [comment]
@vilaboim 

Essa é a lib que o pessoal dos projetos da magazine ta usando. Acredito que é a mais usada.

Na hackathon, eu usei ela e o time do Fred também usou.

**Comment by stanleygomes** [comment]
Pessoal comenta muito sobre a Semantic UI, pois ela tem muitos componentes.

https://react.semantic-ui.com/

**Comment by vilaboim** [comment]
O problema dela é não ser Material Design.

**Comment by stanleygomes** [comment]
beleza!

**Comment by rafael1995** [comment]
Por mim fechou na UI Kit.

Isso também será opcional? Eu acho que deveria.

**Comment by stanleygomes** [comment]
Fechado na Material design UI kit.

acho que pode ser opcional.

Podemos deixar num arquivo com as patterns informando que ela é a recomendada.

**Comment by vilaboim** [comment]
Em projetos Softbox que usam Material Design ela tem que ser obrigatória.
