### ISSUE TITLE
Add example of Trans component

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#145]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to add `html` to a translation, so we need to use a usa case for [Trans component by react-i18next](https://react.i18next.com/latest/trans-component).

**Describe the solution you'd like**
We need a simple example, so you can add a `<strong>` tag to Juggernaut title in `Home/index.jsx`.

![Screen Shot 2020-10-05 at 13 59 23](https://user-images.githubusercontent.com/4191549/95109469-02579780-0713-11eb-90c2-8850686b2a82.png)

**Comment by stanleygomes** [comment]
Can I do this one?

**Comment by vilaboim** [comment]
Go get 'em, Tiger.

**Comment by stanleygomes** [comment]
@fredericofigueira você consegue pegar essa task no meu lugar?
