### ISSUE TITLE
Alterar o padrão de nomenclatura de styled-components

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#146]
**Is your feature request related to a problem? Please describe.**
No início do projeto definimos que os arquivos de estilo seriam chamados `style.js` em vez de `styled.js` para não atrelar a uma ferramenta específica, mas acabamos fazendo isso no nome dos componentes (StyledTitle, StyleTypography, etc.).

**Describe the solution you'd like**
Pensei em deixarmos sem prefixo ou sufixo (Title, Subtitle) e quando precisarmos usar o nome de algum componente do Material-UI usarmos o seguinte padrão:
```js
import TypographyMU from '@material-ui/core/Typography'

export const Typography = styled(TypographyMU)``
```

E em um caso mais específico, em que precisemos usar um componente do MUI e um interno no mesmo arquivo poderia ser assim:
```js
import TypographyMU from '@material-ui/core/Typography'

export const TypographyJug = styled(TypographyMU)``
```
E o uso em um componente React seria assim:
```jsx
<Typography />
<TypographyJug />
```

Qual é a opinião de vocês?

**Comment by stanleygomes** [comment]
Cara, eu acho uma boa. Bora fazer.

**Comment by fredericofigueira** [comment]
Eu gosto da ideia também, bora fazer!

**Comment by marlonmleite** [comment]
Essa opção do `TypographyJug` não é elegante e muito verboso.

Acho que no styled poderia ser assim:

```jsx
import TypographyComponent from '@material-ui/core/Typography'

export const Typography = styled(TypographyComponent)
```

Ou algo assim:
```jsx
import Typo from '@material-ui/core/Typography'

export const Typography = styled(Typo)
```

Tem alguns projetos que acompanhei e o pessoal utiliza puro, sem prefixo ou coloca tudo dentro do import (Porém voto por ser sem prefixo nenhum):
```jsx
import * as S from './styles.js'

<S.Text />
```

**Comment by douglaszaltron** [comment]
Uma sujestão é levar a mesma nomeclatura que a biblioteca usa internamente. (O material-ui utiliza o "Mui" como prefixo)
```javascript
import MuiTypography from '@material-ui/core/Typography'

export const Typography = styled(MuiTypography)
```

no import essa abordagem é bacana, a vantagem é que dessa forma o Typography pode coexistirem tanto o estilizado tanto o importado do components. 

```javascript
import Typography from 'components/Typography' 
import * as Styles from './styles.js' //É uma abordagem semelhante a que o Antd faz, e como o webpack já reconhece o que está sendo utilizado para importar, não tem o problema de tree shaking.

<Typography />
<Styles.Typography />
```

Porém sem prefixo apresenta ser mais confortavél visualmente, e como o cenário acima não é tão comum, prefiro assim.
```javascript
import { Typography } from './styles.js' 

<Typography />
```

**Comment by douglaszaltron** [comment]
Sobre o nome do arquivo ser 'styles' ou 'style', já que esse arquivo pode contém mais de uma estilização de componentes diferente não seria interessante ser em plural?

Em alguns projetos que acompanho, quando se trata de um componente isolado, gosto dessa abordagem.

Ao criar um componente novo:
> Button > index.jsx
> Button > Button.jsx
> Button > Button.style.jsx
> Button > Button.spec.jsx
> Button > Button.story.jsx

```javascript
import { ButtonIcon, ButtonLabel, ButtonShape, ButtonPrimary, ButtonSecondary, ButtonGhost } from './Button.style.jsx' 
```
ou em plural sem o prefix
> Container > Login > index.jsx
> Container > Login > Login.jsx
> Container > Login > styles.jsx

```javascript
import { ContentLeft, ContentRight, PictureIllustration  } from './styles.js' 
```
