### ISSUE TITLE
Arquivos JS ou JSX para os components?

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/juggernaut#15]

**Comment by vilaboim** [comment]
Eu acho importante bater o olho e entender o que cada arquivo faz, e para ficar claro que é um component React prefiro o uso de .jsx.

E como não traz nenhum problema no build - pois o webpack entende a extensão - não existe configuração extra.

**Comment by rafael1995** [comment]
Jsx

**Comment by stanleygomes** [comment]
Jsx
