### ISSUE TITLE
Como organizar os estilos do projeto?

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/juggernaut#16]

**Comment by vilaboim** [comment]
Eu sou adepto do uso de styled-components.
Acho poderoso e fácil de usar, principalmente para criar uma estrutura de temas.

Eu deixo um arquivo style.js na pasta do componente e importo ele no .jsx

**Comment by rafael1995** [comment]
Essa é uma boa discussão. 

Será que devemos deixar isso padronizado? 
Eu concordo com o @vilaboim .. e também temos que ter opções de css globais para o projeto..

**Comment by stanleygomes** [comment]
Eu acho válido sim deixar um padrão de estilização.

Eu ainda tenho um preconceito de usar CSS como javascript, mas não sei se meu preconceito é valido.

**Comment by vilaboim** [comment]
@stanleygomes eu imagino que esse preconceito é o mesmo que rolou quando surgiu o JSX, no fim é só JS, ele compila aquilo tudo.

**Comment by vilaboim** [comment]
@rafael1995 acredito CSS global é consequência, não acho válido já pensar nele no início.
Sempre parto do pressuposto que podemos criar CSS só em componentes.

Quando menos global, melhor.

**Comment by stanleygomes** [comment]
Definido a utilização do modelo styled-components:

https://www.styled-components.com/
