### ISSUE TITLE
NPM ou Yarn?

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/juggernaut#17]

**Comment by vilaboim** [comment]
Não vejo mais vantagem em usar Yarn.
Depois da versão 5 o NPM criou o package-lock, passou a ser determinístico e agora é tão rápido quanto o Yarn.

**Comment by mkny** [comment]
Eu particularmente gosto do yarn. Motivos:
- Pela facilidade de rodar os comandos (`yarn dev` ao invés de `npm run dev`)
- Métodos auxiliares que ele tem pra gestão da node_modules (`yarn install --check-files` e outros da doc)
- Algumas vezes esquecia de colocar a flag `--save` na instalação com o npm, o yarn já é fixado isso no `yarn add`
- Caches otimizados dos packages (reutilização em novos projetos)
- Mais rápido pra inicializar a instalação dos pacotes (percebi isso ao longo do tempo)

Sempre fui npm'ista, mas o yarn se sobressaiu em alguns casos, mesmo com o npm 5.x.
Minha opinião.

**Comment by vilaboim** [comment]
Acho que vamos chegar a lugar nenhum nessa discussão 🤣 
No fim, apenas vamos definir qual arquivo vai pro .gitignore (package-lock.json ou yarn.lock).
Cada um vai usar o que quiser.

Podemos apenas criar uma votação e quem ganhar, ganhou.
Vou fazer 2 comentários abaixo, e vocês curtem o que preferirem.

**Comment by vilaboim** [comment]
npm

**Comment by vilaboim** [comment]
yarn

**Comment by vilaboim** [comment]
Conversando com o @mkny e o Marlon percebemos que precisamos travar o uso do yarn, pois pode haver alguma configuração do .npmrc

**Comment by marlonmleite** [comment]
Existem 2 pontos importantes para avaliarmos:
- Nos benchmarks recentes o yarn em comparação com o npm ganha em 80% dos casos em relação a performance;
- E essa diferença entre eles é maior ainda, quando existe instabilidade na Internet;

Vejam: https://github.com/pnpm/benchmarks-of-javascript-package-managers

**Comment by vilaboim** [comment]
Eu fiz uns testes e o Yarn é bem mais rápido depois que ele gera o lock (o primeiro install é bem lento).

E sobre manter ou não o lock, tem essa issue e o comentário do Sindre Sorhus:
https://github.com/sindresorhus/ama/issues/479#issuecomment-310661514

Eu mudei minha opinião e votaria no Yarn.

**Comment by stanleygomes** [comment]
Definido yarn, agora que o @vilaboim mudou para o dark side.
