### ISSUE TITLE
Padrão de nome de componentes

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/juggernaut#18]
Qual seria o melhor padrão?
/components/Loja/index.js
/components/Loja/index.jsx
/components/Loja/Loja.js
/components/Loja/Loja.jsx

Mandem outras sugestões.

Pessoal ta considerando o caso de ter vários index.js nas abas do VS Code.

É uma anotação válida.

**Comment by vilaboim** [comment]
Se não for index a gente precisaria importar componentes assim: /Loja/Loja.
Acho inviável.

O VSCode tem os breadcrumbs pra diferenciar os arquivos.

**Comment by vilaboim** [comment]
E como comentei na #15, prefiro .jsx, pra ficar claro que é um component React.

**Comment by mkny** [comment]
Concordo com o @vilaboim, a segunda opção parece a mais viável `/components/Loja/index.jsx`

**Comment by rafael1995** [comment]
Também acho que faz mais sentido` /components/Loja/index.jsx`

**Comment by stanleygomes** [comment]
Fechou então: /components/Loja/index.jsx
