### ISSUE TITLE
Utilizar camada para organizar requests Http

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/juggernaut#19]
https://github.com/infinitered/apisauce

Também utilizar o potencial dos interceptors.

**Comment by vilaboim** [comment]
Posso não ter entendido o propósito dele, mas usar apenas o axios não resolve esse problema?

Nos meus projetos em Vue eu sempre crio uma pasta resources e lá dentro um arquivo axios.js (que é a instância do axios) e outros com nomes dos recursos que preciso (users, customers, etc.), então cada recurso importa o axios.js e tem suas rotas de API.

**Comment by mkny** [comment]
Também acho que podemos utilizar dos recursos do axios, para otimizar as requisições com as padronizações e os dicionários, que foram levantados.
O axios tem o `axios.create()` que poderia ser bem explorado, na construção desse esquema.

**Comment by stanleygomes** [comment]
Fechado com axios!!

**Comment by vilaboim** [comment]
@mkny exato, eu uso o axios.create no arquivo axios.js que falei acima.
