### ISSUE TITLE
Patterns

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#2]
Achei esse link que parece ser interessante:
https://reactpatterns.com/

Coloquem aqui os artigos que vocês conhecem que falam de padrões React.

**Comment by rafael1995** [comment]
![estrutura](https://user-images.githubusercontent.com/10281577/53037145-3146ca00-3458-11e9-9316-b3cba0027c03.png)


Segue a estrutura de diretórios que já havíamos definido, se ainda restarem duvidas.. já vamos "matando" isso.

**Comment by rafael1995** [comment]
Definido: Vamos colaborar e verificar se será usado no gandalf

**Comment by marlonmleite** [comment]
Na seção de "Patterns", poderiamos como complemento configurar por default a extensão do eslint para react integrado com o eslint do airbnb, dessa forma garantimos:

Formatações;
Padrões em ordem de função do ciclo de vida do Componente;
Tamanho máximo de linhas;
e várias outras padronizações utéis no dia a dia;
Com essas configurações, conseguimos também configurar o editor para formatar o código conforme essas regras todas as vezes que salvar 1 arquivo.

Mais informações do style guide: https://github.com/airbnb/javascript/tree/master/react
Mais informações do plugin: https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb

O que acham dessa sugestão?

**Comment by rafael1995** [comment]
Fala @marlonmleite !!

**Algumas** dessas questões foram discutidas.. inclusive passando pelas regras dos principais padrões (AirBnb e Standard). 

E então, decidimos seguir o padrão do Standard, mas também manter algumas coisas interessantes do AirBnb.. e foi ai que surgiu o Gandalf Lint e a ideia era seguir com ele no juggernaut.

Vc chegou a ver algo a respeito? 

issue: #13 
https://github.com/SoftboxLab/gandalf-lint

**Comment by marlonmleite** [comment]
Fala @rafael1995, o @vilaboim me explicou mesmo essas decisões.

Acho o que podemos discutir depois é adotar algum style guide para guiar pessoas mais iniciantes no React para pegar algumas boas práticas.

**Comment by joseasousa** [comment]
Pattern de estrutura do redux 
[Ducks](https://blog.rocketseat.com.br/estrutura-redux-escalavel-com-ducks/)

**Comment by marlonmleite** [comment]
Esse padrão do Ducks quando você escala ele, fica muito complicado a manutenção.
Uma estratégia que evoluimos é que cada container tenha uma pasta com suas actions, reducers e etc.

Mas isso tem que ser bem analisado, pois se olhar não deveriamos criar reducer para tudo (todas as páginas e etc), deveriamos criar apenas para coisas que deveriam ficar globais.

Mas é complicado esse pattern, acredito que seria produtivo em futuras discussões, pessoas diferentes opinar e também pesquisar a evolução do redux para compararmos as soluções e também as propostas de cada um.

**Comment by joseasousa** [comment]
Acredito tambem que devemos usar redux apenas para os objetos globais, objetos de uma classe podemos usar hooks ou o próprio stado do objeto
E so so quisermos compartilhar um objeto globalmente, podemos usar a contest API
