### ISSUE TITLE
Controle de rotas - react Router ou react-router-dom?

### ISSUE THREAD

**Issue by rafael1995** [SoftboxLab/juggernaut#20]
Já iniciamos essa discussão na última reunião do Capitulo, mas apenas para confirmarmos e deixar registrado.. 

Vamos usar o que para controle de rotas, react-router ou react-router-dom ?

Minha opinião: react-router-dom

**Comment by mkny** [comment]
@rafael1995 vi aqui que o que eu tinha mencionado no final do capitulo, sobre o `react-router-redux`, ele foi descontinuado.
O `react-router` é a base pro `react-router-dom`.
A questão que deve ser levantada e é válida, é com relação ao componente de history, do react-router
- `<MemoryRouter>`
- `<HashRouter>`
- `<BrowserRouter>`

Acredito que o mais tranquilo e bacana de se trabalhar é o `<BrowserRouter>`.

**Comment by vilaboim** [comment]
@rafael1995 como nosso projeto vai focar em web, só o react-router-dom resolve.
https://stackoverflow.com/questions/42684809/react-router-vs-react-router-dom-when-to-use-one-or-the-other

**Comment by vilaboim** [comment]
@mkny eu voto em BrowserRouter, com o vue-router eu sempre uso o mode: history, que é equivalente.

**Comment by stanleygomes** [comment]
Será implementado na issue #30
