### ISSUE TITLE
Immutable

### ISSUE THREAD

**Issue by mkny** [SoftboxLab/juggernaut#21]
É relevante implementar na arquitetura planejada?

**Comment by vilaboim** [comment]
Podíamos tentar apenas aplicar os conceitos de imutabilidade na implementação do Redux, sem instalar mais uma dependência.

**Comment by marlonmleite** [comment]
Concordo com o @vilaboim, pois implementar lib de Immutable cria uma curva de complexidade desnecessária inicialmente no projeto.
