### ISSUE TITLE
Criar um webpack config com alias para as pastas principais do projeto

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/juggernaut#23]
**Objetivo:** Simplificar a importação.

**Import atual:**
import Example1 from '../components/Example1';
import Example2 from '../../utils/Example2';
import Example3 from '../../../store/Example3';

**Import desejado:**
import Example1 from 'Components/Example1';
import Example2 from 'Utils/Example2';
import Example3 from 'Store/Example3';

### **webpack.config.shared.js**

```
/*  --  webpack.config.shared.js  --  */
export const sharedConfig = {
    alias: {
        'Utils': path.resolve(__dirname, '../src/utils/'),
        'Components': path.resolve(__dirname, '../src/components/'),
    },
};

```

**Comment by vilaboim** [comment]
Creio que isso só funcione fazendo o eject.

**Comment by rafael1995** [comment]
definido: Temos que confirmar se é somente fazendo o eject. @vilaboim

**Comment by stanleygomes** [comment]
Ideia ejetada.
