### ISSUE TITLE
Configurar o i18n na estrutura de pastas

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/juggernaut#28]
Configurar dentro da pasta common.

**Comment by marlonmleite** [comment]
Sugestão: [React Intl](https://github.com/yahoo/react-intl)

**Comment by vilaboim** [comment]
O @marlonmleite fez uma pesquisa no slack React Brasil e a maioria dos devs usam o react-i18-next.
E como ele atende o que pretendíamos com o react-intl, decidimos mudar.

**Comment by marlonmleite** [comment]
#46
