### ISSUE TITLE
Estrutura de Diretórios

### ISSUE THREAD

**Issue by rafael1995** [SoftboxLab/juggernaut#3]
Galera, segue a estrutura de diretórios que definimos na época da moo-cli. 

Futuramente, ao iniciar um projeto através da cli a ideia é termos essa estrutura:

![estrutura](https://user-images.githubusercontent.com/10281577/53037416-ec6f6300-3458-11e9-993b-5b1a45363cc1.png)

**Comment by vilaboim** [comment]
@rafael1995, mande prints de dentro das pastas components (que não está aí), store e views.

**Comment by stanleygomes** [comment]
@vilaboim 

O rafael tinha feito a estrutura nesse repositório:
https://github.com/rafael1995/struct-example

Fiz um pull request como essa estrutura.

**Comment by vilaboim** [comment]
#5

**Comment by vilaboim** [comment]
Alguns links úteis:
https://github.com/marlonmleite/react-boilerplate
https://daveceddia.com/react-project-structure/

**Comment by rafael1995** [comment]
Estrutura Inicial:

src/components: Components of React to be shared and reused in the project;
src/containers: Page components that apply business knowledge and present themselves as pages;
src/common: Resources, Utilities, constants, configurations, i18n and others.
src/store: State configuration with Redux;
src/assets: static files (fonts, icons, images)
src/docz: Docs configuration
eslintrc:  Gandalf Lint
 

Futuramente: 
stub: Routes of mock backend API`s.
Pre commit/push hooks:  #9

**Comment by stanleygomes** [comment]
Padrão definido.
