### ISSUE TITLE
configurar styled-components

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/juggernaut#37]
https://styled-components.com

Onde colocar o CSS global?

**Comment by marlonmleite** [comment]
@stanleygomes acredito ser ideal criar dentro de src/common, poderia ser dentro de utils/style.js ou algo semelhante. Seria interessante ouvir outra sugestões também.

**Comment by stanleygomes** [comment]
Boa @marlonmleite 

Gostei de utils/style.js

vamos esperar mais opiniões do pessoal

**Comment by rafael1995** [comment]
Por mim, pode ser como @marlonmleite disse:
 common/utils/style.js

**Comment by marlonmleite** [comment]
Implementação executada no PR: https://github.com/SoftboxLab/juggernaut/pull/40
