### ISSUE TITLE
instalar Redux no projeto, e qual alternativa para redux assíncrono Thunk ou saga

### ISSUE THREAD

**Issue by joseasousa** [SoftboxLab/juggernaut#49]
Artigo comparando ambas
[redux thunk vs Saga](http://blog.jakegardner.me/redux-thunk-vs-saga/)

**Comment by joseasousa** [comment]
Artigo comparando ambas
[redux thunk vs Saga](http://blog.jakegardner.me/redux-thunk-vs-saga/)

**Comment by joseasousa** [comment]
Sugestao de lib para persistencia do redux  [redux-persist](https://github.com/rt2zz/redux-persist)

**Comment by mkny** [comment]
Acho que o redux-saga é uma boa opção. Aplicações apenas com o thunk acaba sendo muito moroso nas chamadas de funções.
