### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/juggernaut#52]
Onde vamos deixar a documentação do projeto?

**Comment by joseasousa** [comment]
pode criar um gitHub pages do projeto com a doc

**Comment by marlonmleite** [comment]
Acredito que a documentação deve ser no pŕoprio readme, pois não temos muitas coisas para falar, mas temos que colocar links utéis para utilização de determinados itens (exemplo material-ui, styled-components e etc);

**Comment by marlonmleite** [comment]
Documentação de execução base para substituir o README deveria ser algo assim + os complementos de bibliotes e outros pertinentes ao boilerplate:

# my-front-name



### Starting

Clone repo and enter in folder

```shel
git clone https://gitlab.softbox.com.br/{ORG}/{REPO}.git
```

Install dependencies:

```shel
npm install
```

Run this project:

```shel
npm run start
```

Go to: [http://localhost:3000/](http://localhost:3000/)


### Project structure

- **src/assets**: Static files (images, fonts and icons);
- **src/components**: Components of React to be shared and reused in the project;
- **src/common**: Utilities, resources, constants, assets, configurations, i18n and others;
- **src/containers**: Page components that apply business knowledge and present themselves as pages;
- **src/routes**: Routes of app to be used by SPA and user navigation;
- **src/store**: State configuration with Redux;
- **docs**: Docs configuration.


### Continuos Integration
For build and run this project, you need run the follow steps:
1) Clone repo and enter in folder
2) Set the ENV ```CI=true``` (The next steps require this for execute scripts inline)
3) `npm install`
4) `npm run eslint`
5) `npm run test`
6) `npm run build`
7) Copy the build files from ** build ** folder generated after step 5


### References

This project was bootstrapped with [Juggernaut](https://github.com/SoftboxLab/juggernaut).
