### ISSUE TITLE
Ideias para Hello World do repositório

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/juggernaut#53]
Deixem suas sugestões.

**Comment by rafael1995** [comment]
Na minha opinião,  tela de login deve ter:

- Uma mensagem com redirecionamento para criação de issues aqui no repositório. 
- Uma animação simples 
- E uma foto do juggernaut

**Comment by stanleygomes** [comment]
Colocar o link para "contribua" e "documentação"

**Comment by vilaboim** [comment]
#51
