### ISSUE TITLE
Sugestao de Lib Para Formuarios

### ISSUE THREAD

**Issue by joseasousa** [SoftboxLab/juggernaut#54]
Sugestao de Lib para validação de formularios [Formik](https://jaredpalmer.com/formik/docs/guides/validation) 
Ela combinada com o [Yup](https://github.com/jquense/yup) torna a validacao de formularios bem mais simples

**Comment by marlonmleite** [comment]
Eu apoio o uso do Formik e também acredito que na inclusão da lib, devemos colocar HOC para conexão automatica de fields e etc.

A questão do yup podemos deixar ela como opcional (fácil de ser retirado), pois o size da lib é grande e em projetos que necessitam performance isso prejudica muito.

**Comment by mkny** [comment]
Já utilizei o [redux-form](https://github.com/erikras/redux-form). Apesar de complexo, ele é bem completo e customizável.

**Comment by vilaboim** [comment]
Essa integração vai depender da library de componentes. O que for definido tem que vir pra cá.
