### ISSUE TITLE
Configurar Dockerfile

### ISSUE THREAD

**Issue by marlonmleite** [SoftboxLab/juggernaut#55]
Criar a configuração base de Docker para deploy pelo time de infra.

**Comment by marlonmleite** [comment]
Já estou trabalhando nisso no projeto da Magalu e assim que tiver validado e funcionando com a Infra, eu abro o PR aqui.

**Comment by stanleygomes** [comment]
Boa! Tem algo que precisa pensar para kubernetes?

**Comment by vilaboim** [comment]
@marlonmleite isso é realmente necessário no Juggernaut?

Processos de deploy variam entre projetos, alguns vão usar Docker, outro CircleCI, outros Jenkins, etc.

**Comment by stanleygomes** [comment]
@vilaboim 

É por que o dockerfile independe da ferramenta de deploy. Seria só para construir uma máquina com todos os requisitos do projeto para ser usada para deploy da aplicação.

Ai no circleci, jenkins, gitlab ci, bitbucket ci etc, cada um tem sua configuração num arquivo  (.YML). Aí este arquivo eu já acho que não precisa.

**Comment by vilaboim** [comment]
Mas é um projeto muito simples para precisar de Docker.
Pra montar o ambiente você seleciona a versão do node e roda yarn build.
Realmente não vejo necessidade nisso.

**Comment by marlonmleite** [comment]
Essa parte do Docker é desnecessário, pois a unica coisa que precisa para nosso front funcionar é o NPM.
O projeto de front caso dependa de backend, o backend em si que deve fornecer meios de executarmos local seja com docker ou sem para testar o front chamando o backend.

Quando o time de infra vai configurar o projeto nosso de front para deploy, eles ignoram o nosso Dockerfile e utilizam 1 no padrão deles (que tem utilidade apenas no servidor)
