### ISSUE TITLE
Criação da CLI

### ISSUE THREAD

**Issue by mkny** [SoftboxLab/juggernaut#62]
Seria interessante termos uma CLI para agilizar tasks de desenvolvimento do projeto? Ex:
`jugger create component` ou com alias `jugger cc`
`jugger create container` ou com alias `jugger ccom`
`jugger create saga` ou com alias `jugger cs`
E por aí vai...
Seria interessante também, vincular ao projeto [moo-cli](https://github.com/SoftboxLab/moo-cli).

**Comment by vilaboim** [comment]
O Juggernaut será adicionado a moo-cli.
