### ISSUE TITLE
Adicionar links na documentação

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#69]
Exemplo:

Why React? [LINK]
Why Formik? [LINK]

**Comment by rafael1995** [comment]
Why Formik? https://bit.ly/2V8zi94

Why Axios? https://bit.ly/2lvRZmi

Why Material-UI? https://bit.ly/2m5SUvi

Why react-i18next? https://bit.ly/2J7nfag

**Comment by rafael1995** [comment]
Why Formik?

Formik é uma pequena biblioteca que nos ajuda com as 3 partes essenciais em formulários:

- Obtendo valores dentro e fora do estado do formulário
- Validação e mensagens de erro
- Manipulando envio de formulário

E não tem ligações com o redux :+1:

**Comment by rafael1995** [comment]
Why Axios?

- Intercept request and response
- Make XMLHttpRequests from the browser
- Supports the Promise API
- Transform request and response data
- Cancel requests
- Automatic transforms for JSON data
- Client side support for protecting against XSRF
