### ISSUE TITLE
Add Code coverage

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#83]
**Is your feature request related to a problem? Please describe.**
When we run `yarn test:coverage` there is almost no coverage.

**Describe the solution you'd like**
Write tests to all files listed on code coverage report.

**Comment by arnabk** [comment]
@vilaboim You may want to narrow down the scope of this task. If we are supposed to write tests for all files and then add the coverage command, then its a very long work. If you just want to see the test coverage command working and do not really care about coverage percentage in this task, I can help you getting the command added (and may be add one unit to show you that the commands work). 

Once that is done, you can open separate tickets to get unit tests added for all other files.

**Comment by vilaboim** [comment]
@arnabk we already have a `test:coverage` script provided by CRA, we need to write unit tests for all files.
I'll split this issue into smaller ones.
