### ISSUE TITLE
Add Button component

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#84]
**Is your feature request related to a problem? Please describe.**
We need to add a button component bypassing material-ui button.

**Describe alternatives you've considered**
A imagined a button importing material-ui button and then exporting, easy peasy.

**Comment by Windrushfarer** [comment]
I'll take this

**Comment by ibokg** [comment]
Hi! Can I try doing it?

**Comment by stanleygomes** [comment]
Sure!
