### ISSUE TITLE
Add Circular Progress Component

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#85]
**Is your feature request related to a problem? Please describe.**
We need to add a loader component bypassing material-ui [circular progress](https://material-ui.com/components/progress/).

**Describe alternatives you've considered**
I imagined a loader component importing material-ui circular progress and then exporting.

**Comment by Bus42** [comment]
I'd like to tackle this one : )

**Comment by Bus42** [comment]
Okay, I went ahead and made the component but I can't do a PR

**Comment by vilaboim** [comment]
@Bus42 be our guest.
