### ISSUE TITLE
Change commons for common

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#86]
**Describe the bug**
The folder of common assets is named wrongly, should name [`common`](https://dictionary.cambridge.org/us/dictionary/english/common)

**Additional context**
The word `Commons` has another [meaning](https://dictionary.cambridge.org/us/dictionary/english/commons?q=Commons)

**Comment by marlonmleite** [comment]
Hey, but the word commons is based in common's.

**Comment by vilaboim** [comment]
This is wrong the same way.
We usually use the apostrophe to show [possession](https://www.grammarbook.com/punctuation/apostro.asp), and here is not the case.

**Comment by ehuange** [comment]
@vilaboim I'd like to take this issue please.

**Comment by vilaboim** [comment]
@ehuange be our guest.
