### ISSUE TITLE
Add CI / Docker file sample

### ISSUE THREAD

**Issue by mkny** [SoftboxLab/juggernaut#87]
**Is your feature request related to a problem? Please describe.**
Wouldn't be great if the project include some Docker / CI examples, on the most common  platforms?
Ex:
- circleci
- gitlab-ci
- travis-ci
- azure devops
- drone-ci

**Describe the solution you'd like**
I've found a repository from react-native-community [here](https://github.com/react-native-community/ci-sample), that make use of some examples that could help a lot, on the building, deployment, ci process.

**Describe alternatives you've considered**
An good alternative could be a simple .md file, to work as a guide.

**Additional context**
Some performance improvements could be done in the ci process or something like memory optimization, avoid source map generation or something like that.

**Comment by vilaboim** [comment]
Great idea :clap:

**Comment by kmjayadeep** [comment]
Shall I work on travis-ci example

**Comment by vilaboim** [comment]
@kmjayadeep it would be great, thanks.
