### ISSUE TITLE
Add link to Juggernaut Demo

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#88]
**Is your feature request related to a problem? Please describe.**
We need to link [Juggernaut Demo](https://github.com/SoftboxLab/juggernaut-demo) to this repo.

**Describe the solution you'd like**
Add a hyperlink to the README.

**Comment by susanahan** [comment]
@vilaboim can i work on this?

**Comment by vilaboim** [comment]
@susanahan be our guest.

**Comment by susanahan** [comment]
@vilaboim please assign to me 😄
