### ISSUE TITLE
Pre commit/push hooks

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/juggernaut#9]
Acho muito interessante rodar lint e testes antes de commits e push, o que acham de colocar isso na config?

https://levelup.gitconnected.com/using-pre-commit-and-pre-push-git-hooks-in-a-react-project-6c83431ef2bd

**Comment by rafael1995** [comment]
Muito bom e aparentemente bem fácil de ser configurado.
Acho interessante isso ser **personalizado** no momento da criação do projeto e não vejo como uma prioridade na nossa fase inicial.

**Comment by vilaboim** [comment]
Ok, podemos fazer uma lista de tasks e essa fica no fim.

**Comment by ramonvlopes** [comment]
Acho bem bacana essa questão do pre-commit. Podemos avaliar bem a possibilidade de deixar um padrão básico de configuração, mas talvez não deixar essa configuração exposta inicialmente. Apenas deixar para o usuário, utilizar ou não.

**Comment by vilaboim** [comment]
@ramonvlopes, temos que avaliar aquela questão dos branches que conversamos.
Vou abrir uma issue para isso.

**Comment by vilaboim** [comment]
#11

**Comment by marlonmleite** [comment]
Essa questão de pré-commit é ideal no momento de push, pois o commit você executa para algo parcial e até com problemas e não tudo 100% pronto.
Porém no momento do push, não pode acontecer com testes quebrados e problemas de eslint.
