### ISSUE TITLE
Update material-ui

### ISSUE THREAD

**Issue by marlonmleite** [SoftboxLab/juggernaut#91]
**Is your feature request related to a problem? Please describe.**
Update the version of **@material-ui/core** and **@material-ui/icons**.

**Comment by Ania-chan** [comment]
Hi! Can I try doing this issue? 🙏

**Comment by stanleygomes** [comment]
Hi @Ania-chan !!

Sure! It would be great.

**Comment by Ania-chan** [comment]
@stanleygomes Thanks! I'll let you know if I encounter any blockers

**Comment by Ania-chan** [comment]
@marlonmleite This issue can be closed
